/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lottery {
  'id' : LotteryId,
  'winningNumber' : [] | [bigint],
  'name' : string,
  'drawDate' : Time,
  'description' : string,
  'isActive' : boolean,
  'isDrawn' : boolean,
  'maxTickets' : bigint,
  'price' : bigint,
}
export type LotteryId = bigint;
export type SessionId = string;
export interface Ticket {
  'ticketNumber' : bigint,
  'lotteryId' : LotteryId,
  'sessionId' : SessionId,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'page' : string,
  'timestamp' : Time,
  'sessionId' : SessionId,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLottery' : ActorMethod<
    [string, string, bigint, Time, bigint],
    LotteryId
  >,
  'deleteLottery' : ActorMethod<[LotteryId], undefined>,
  'getAllLotteries' : ActorMethod<[], Array<Lottery>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLottery' : ActorMethod<[LotteryId], Lottery>,
  'getRecentVisits' : ActorMethod<[bigint], Array<Visit>>,
  'getTicketsByLottery' : ActorMethod<[LotteryId], Array<Ticket>>,
  'getTicketsBySession' : ActorMethod<[SessionId], Array<Ticket>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'getVisitsBySession' : ActorMethod<[SessionId], Array<Visit>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseTicket' : ActorMethod<[SessionId, LotteryId], bigint>,
  'recordVisit' : ActorMethod<[SessionId, string], undefined>,
  'updateLottery' : ActorMethod<
    [LotteryId, string, string, bigint, Time, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];