/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LotteryId = IDL.Nat;
export const Lottery = IDL.Record({
  'id' : LotteryId,
  'winningNumber' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'drawDate' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'isDrawn' : IDL.Bool,
  'maxTickets' : IDL.Nat,
  'price' : IDL.Nat,
});
export const SessionId = IDL.Text;
export const Visit = IDL.Record({
  'page' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : SessionId,
});
export const Ticket = IDL.Record({
  'ticketNumber' : IDL.Nat,
  'lotteryId' : LotteryId,
  'sessionId' : SessionId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLottery' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Nat],
      [LotteryId],
      [],
    ),
  'deleteLottery' : IDL.Func([LotteryId], [], []),
  'getAllLotteries' : IDL.Func([], [IDL.Vec(Lottery)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLottery' : IDL.Func([LotteryId], [Lottery], ['query']),
  'getRecentVisits' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'getTicketsByLottery' : IDL.Func([LotteryId], [IDL.Vec(Ticket)], ['query']),
  'getTicketsBySession' : IDL.Func([SessionId], [IDL.Vec(Ticket)], ['query']),
  'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'getVisitsBySession' : IDL.Func([SessionId], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseTicket' : IDL.Func([SessionId, LotteryId], [IDL.Nat], []),
  'recordVisit' : IDL.Func([SessionId, IDL.Text], [], []),
  'updateLottery' : IDL.Func(
      [LotteryId, IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LotteryId = IDL.Nat;
  const Lottery = IDL.Record({
    'id' : LotteryId,
    'winningNumber' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'drawDate' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'isDrawn' : IDL.Bool,
    'maxTickets' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const SessionId = IDL.Text;
  const Visit = IDL.Record({
    'page' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : SessionId,
  });
  const Ticket = IDL.Record({
    'ticketNumber' : IDL.Nat,
    'lotteryId' : LotteryId,
    'sessionId' : SessionId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLottery' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Nat],
        [LotteryId],
        [],
      ),
    'deleteLottery' : IDL.Func([LotteryId], [], []),
    'getAllLotteries' : IDL.Func([], [IDL.Vec(Lottery)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLottery' : IDL.Func([LotteryId], [Lottery], ['query']),
    'getRecentVisits' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'getTicketsByLottery' : IDL.Func([LotteryId], [IDL.Vec(Ticket)], ['query']),
    'getTicketsBySession' : IDL.Func([SessionId], [IDL.Vec(Ticket)], ['query']),
    'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'getVisitsBySession' : IDL.Func([SessionId], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseTicket' : IDL.Func([SessionId, LotteryId], [IDL.Nat], []),
    'recordVisit' : IDL.Func([SessionId, IDL.Text], [], []),
    'updateLottery' : IDL.Func(
        [LotteryId, IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };