/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lottery {
    id: LotteryId;
    winningNumber?: bigint;
    name: string;
    drawDate: Time;
    description: string;
    isActive: boolean;
    isDrawn: boolean;
    maxTickets: bigint;
    price: bigint;
}
export type Time = bigint;
export type SessionId = string;
export interface Ticket {
    ticketNumber: bigint;
    lotteryId: LotteryId;
    sessionId: SessionId;
}
export type LotteryId = bigint;
export interface Visit {
    page: string;
    timestamp: Time;
    sessionId: SessionId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLottery(name: string, description: string, price: bigint, drawDate: Time, maxTickets: bigint): Promise<LotteryId>;
    deleteLottery(id: LotteryId): Promise<void>;
    getAllLotteries(): Promise<Array<Lottery>>;
    getCallerUserRole(): Promise<UserRole>;
    getLottery(id: LotteryId): Promise<Lottery>;
    getRecentVisits(count: bigint): Promise<Array<Visit>>;
    getTicketsByLottery(lotteryId: LotteryId): Promise<Array<Ticket>>;
    getTicketsBySession(sessionId: SessionId): Promise<Array<Ticket>>;
    getTotalVisits(): Promise<bigint>;
    getVisitsBySession(sessionId: SessionId): Promise<Array<Visit>>;
    isCallerAdmin(): Promise<boolean>;
    purchaseTicket(sessionId: SessionId, lotteryId: LotteryId): Promise<bigint>;
    recordVisit(sessionId: SessionId, page: string): Promise<void>;
    updateLottery(id: LotteryId, name: string, description: string, price: bigint, drawDate: Time, maxTickets: bigint): Promise<void>;
}
import type { Lottery as _Lottery, LotteryId as _LotteryId, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLottery(arg0: string, arg1: string, arg2: bigint, arg3: Time, arg4: bigint): Promise<LotteryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLottery(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLottery(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteLottery(arg0: LotteryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLottery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLottery(arg0);
            return result;
        }
    }
    async getAllLotteries(): Promise<Array<Lottery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLotteries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLotteries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLottery(arg0: LotteryId): Promise<Lottery> {
        if (this.processError) {
            try {
                const result = await this.actor.getLottery(arg0);
                return from_candid_Lottery_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLottery(arg0);
            return from_candid_Lottery_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentVisits(arg0: bigint): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentVisits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentVisits(arg0);
            return result;
        }
    }
    async getTicketsByLottery(arg0: LotteryId): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsByLottery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsByLottery(arg0);
            return result;
        }
    }
    async getTicketsBySession(arg0: SessionId): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsBySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsBySession(arg0);
            return result;
        }
    }
    async getTotalVisits(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVisits();
            return result;
        }
    }
    async getVisitsBySession(arg0: SessionId): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitsBySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitsBySession(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchaseTicket(arg0: SessionId, arg1: LotteryId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseTicket(arg0, arg1);
            return result;
        }
    }
    async recordVisit(arg0: SessionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit(arg0, arg1);
            return result;
        }
    }
    async updateLottery(arg0: LotteryId, arg1: string, arg2: string, arg3: bigint, arg4: Time, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLottery(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLottery(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_Lottery_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lottery): Lottery {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LotteryId;
    winningNumber: [] | [bigint];
    name: string;
    drawDate: _Time;
    description: string;
    isActive: boolean;
    isDrawn: boolean;
    maxTickets: bigint;
    price: bigint;
}): {
    id: LotteryId;
    winningNumber?: bigint;
    name: string;
    drawDate: Time;
    description: string;
    isActive: boolean;
    isDrawn: boolean;
    maxTickets: bigint;
    price: bigint;
} {
    return {
        id: value.id,
        winningNumber: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.winningNumber)),
        name: value.name,
        drawDate: value.drawDate,
        description: value.description,
        isActive: value.isActive,
        isDrawn: value.isDrawn,
        maxTickets: value.maxTickets,
        price: value.price
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lottery>): Array<Lottery> {
    return value.map((x)=>from_candid_Lottery_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
